version: 2.1
jobs:
  build:
    working_directory: /dockerapp1
    steps:
      - checkout
      - setup_remote_docker
          version: 19.03.13
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            apk add --no-cache make
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            sudo make build
            sudo make run