name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Start
        run: make run
      - name: Test
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="test/Test Suites/Simple Test Suites Collection" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
